title: "Share Study Blog"
email: blog@sharestudy.in
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Zak
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  zak:
    name: Zakir Ayoub
    display_name: Zakir Ayoub
    avatar: 'assets/images/sal.png'
    email: author@sharestudy.in
    web: https://blog.sharestudy.in
    twitter: https://twitter.com/imzakirayoub
    description: "Founder of Share Study and primary author of the Share Study Blog. Passionate about education, technology, and creating resources that empower students to achieve excellence."

# Social
social:
  whatsapp: https://twitter.com/bstartercom

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
